/**
 * @description       : 
 * @author            : Amit Kumar
 * @group             : 
 * @last modified on  : 06-30-2021
 * @last modified by  : Amit Kumar
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   06-30-2021   Amit Kumar   Initial Version
**/
public inherited sharing class UpdatedHttpCalloutMock implements HttpCalloutMock{
    public HttpResponse respond(HttpRequest request){
        return null;
    }
}

